//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public long accountId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phoneNumber { get; set; }
        public string basedIn { get; set; }
        public string classifiedRole { get; set; }
        public string jobseekingStatus { get; set; }
        public string availability { get; set; }
        public string highestEducation { get; set; }
        public string workType { get; set; }
        public string Preferredlocations { get; set; }
        public string ResumeFileName { get; set; }
        public bool PersonalInformationUpdated { get; set; }
        public bool QualificationSkillsUpdated { get; set; }
        public bool CurrentStatusUpdated { get; set; }
        public bool ResumeUpdated { get; set; }
        public string accountKey { get; set; }
        public System.DateTime createdOn { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public long modifiedBy { get; set; }
        public int accountStatus { get; set; }
        public bool isDeleted { get; set; }
    }
}
