//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer
    {
        public long employerId { get; set; }
        public long companyId { get; set; }
        public string employerFirstName { get; set; }
        public string employerLastName { get; set; }
        public string employerEmail { get; set; }
        public string employerPhoneNumber { get; set; }
        public string employerPassword { get; set; }
        public string employerDesignation { get; set; }
        public string employerKey { get; set; }
        public System.DateTime createdOn { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public long modifiedBy { get; set; }
        public int accountStatus { get; set; }
        public bool isDeleted { get; set; }
    }
}
