//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class offcampus4uEntities : DbContext
    {
        public offcampus4uEntities()
            : base("name=offcampus4uEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<admin> admins { get; set; }
        public DbSet<applyJob> applyJobs { get; set; }
        public DbSet<BankDetail> BankDetails { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<employer> employers { get; set; }
        public DbSet<highestEducation> highestEducations { get; set; }
        public DbSet<job> jobs { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<tutorialCategory> tutorialCategories { get; set; }
        public DbSet<video> videos { get; set; }
        public DbSet<wallet> wallets { get; set; }
        public DbSet<walletTransaction> walletTransactions { get; set; }
        public DbSet<withdrawal> withdrawals { get; set; }
    }
}
