//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet
    {
        public wallet()
        {
            this.walletTransactions = new HashSet<walletTransaction>();
        }
    
        public long walletId { get; set; }
        public long accountId { get; set; }
        public string walletBalance { get; set; }
        public long createdBy { get; set; }
        public System.DateTime createdOn { get; set; }
        public System.DateTime modifiedOn { get; set; }
        public long modifiedBy { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual account account { get; set; }
        public virtual ICollection<walletTransaction> walletTransactions { get; set; }
    }
}
